openapi: 3.0.3
info:
  title: Message Api
  description: Message Apiスキーマ
  version: 1.0.0
tags:
  - name: user
    description: ユーザー関係
  - name: auth
    description: 認証関係
  - name: twitter
    description: twitter関係
  - name: dm
    description: dm関係
  - name: line
    description: line関係
paths:
  /login:
    post:
      tags:
        - auth
      summary: ログイン
      description: ログイン
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas/request/loginRequest.yaml"
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
components:
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
